services:
  backend:
    image: ghcr.io/yeganemehr/news-hive:master
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      APP_NAME: News Hive
      APP_ENV: production
      APP_KEY: $APP_KEY
      APP_URL: http://your-hostname.com
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: $DB_PASSWORD
      CACHE_STORE: database
      SESSION_DRIVER: database
      GARDIAN_API_KEY: $GARDIAN_API_KEY
      NYTIMES_API_KEY: $NYTIMES_API_KEY

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment: 
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: laravel
      MARIADB_DATABASE: laravel
      MARIADB_PASSWORD: $DB_PASSWORD
