name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Check code style
      run: vendor/bin/pint --test

    - name: Run tests
      run: php artisan test --coverage

    - name: Analyze OpenAPI
      run: |
        touch database/database.sqlite
        echo "APP_ENV=local" > .env
        echo "APP_KEY=" >> .env
        php artisan key:generate
        php artisan migrate
        php artisan scramble:analyze
